import type { RoadmapDay, RoadmapProject, RoadmapTrack } from "./types";
import { DEFAULT_TIME_BLOCKS, type RoadmapDefinition } from "./roadmap-core";

export const YEAR_ROADMAP_ID = "backend-cloud-12-month";

const MONTHS: Record<number, string> = {
  1: "Month 1 — DSA + Backend Foundations",
  2: "Month 2 — DSA + Backend",
  3: "Month 3 — Backend Engineering",
  4: "Month 4 — Serious Backend",
  5: "Month 5 — Redis, Messaging, Production",
  6: "Month 6 — System Design",
  7: "Month 7 — Docker + DevOps",
  8: "Month 8 — Azure Fundamentals",
  9: "Month 9 — Azure Developer",
  10: "Month 10 — Azure Enterprise",
  11: "Month 11 — SQL + Data Engineering",
  12: "Month 12 — Enterprise Engineering",
};

export const YEAR_MONTH_GOALS: Record<number, string> = {
  1: "Programming fundamentals and DSA: Big O, arrays, hash maps, two pointers, stacks, and queues.",
  2: "Linked lists, recursion, binary search, trees, and graphs — still building small backend projects.",
  3: "Backend becomes the focus: HTTP, NestJS architecture, PostgreSQL, and authentication.",
  4: "Security, testing, files, external APIs, and background jobs.",
  5: "Redis, query optimization, messaging, and a deployable production API.",
  6: "Think like a senior engineer. Design systems, then document BeautiLink.",
  7: "Docker, real Git workflow, and a CI/CD pipeline that deploys your backend.",
  8: "AZ-900: cloud concepts, storage, compute, identity, and security.",
  9: "AZ-204-style development: App Service, Functions, Storage, and Azure SQL.",
  10: "Service Bus, Entra ID, Key Vault, and Application Insights.",
  11: "SQL Server, advanced SQL, ETL, and Azure Data Factory.",
  12: "Enterprise integrations, a security audit, and one serious capstone.",
};

function tasks(id: string, labels: string[]) {
  return labels.map((label, i) => ({ id: `${id}-${i + 1}`, label }));
}

function project(
  id: string,
  title: string,
  track: RoadmapTrack,
  labels: string[],
  description?: string,
): RoadmapProject {
  return { id, title, track, description, tasks: tasks(id, labels) };
}

function dsaTask(week: number): string {
  if (week <= 8) {
    return "DSA: 4–5 foundation problems. Explain time and space complexity yourself.";
  }
  if (week <= 16) {
    return "DSA: 5 medium problems. Understand them — don't collect copied solutions.";
  }
  if (week <= 24) {
    return "DSA: 5–7 problems across trees, graphs, recursion, and DP.";
  }
  if (week <= 36) {
    return "DSA: 5 mixed interview problems.";
  }
  return "DSA: 5–7 timed interview problems. Target 150–200 well-understood problems by year end.";
}

function week(opts: {
  n: number;
  month: number;
  title: string;
  goal: string;
  learn: string[];
  practice?: string[];
  buildTitle: string;
  build: string[];
  buildTrack?: RoadmapTrack;
  review?: string[];
  checklist?: string[];
  mini?: boolean;
  reviewDay?: boolean;
}): RoadmapDay {
  const id = `w${opts.n}`;
  const projects: RoadmapProject[] = [
    project(`${id}-learn`, "Learn", "shared", opts.learn, "Mon–Tue · 1–1.5h"),
  ];
  if (opts.practice?.length) {
    projects.push(
      project(`${id}-practice`, "Practice", "shared", opts.practice, "Drills, not tutorials"),
    );
  }
  projects.push(
    project(
      `${id}-build`,
      "Build",
      opts.buildTrack ?? "backend",
      opts.build,
      opts.buildTitle,
    ),
  );
  projects.push(
    project(`${id}-review`, "Review", "shared", [
      dsaTask(opts.n),
      "Write your own notes. Don't copy the course.",
      "Saturday (2–3h) is the project session. Sunday: finish, document, or rest.",
      ...(opts.review ?? []),
    ], "Fri review + weekend"),
  );

  return {
    dayNumber: opts.n,
    week: opts.month,
    weekLabel: MONTHS[opts.month],
    title: opts.title,
    goal: opts.goal,
    topics: opts.learn,
    task: opts.buildTitle,
    checklist: opts.checklist,
    projects,
    isMiniProject: opts.mini,
    isReviewDay: opts.reviewDay,
  };
}

export const YEAR_ROADMAP_WEEKS: RoadmapDay[] = [
  week({
    n: 1,
    month: 1,
    title: "Big O + arrays",
    goal: "Reason about time and space, then prove it with an algorithm playground.",
    learn: [
      "Big O notation",
      "Time complexity",
      "Space complexity",
      "Arrays",
      "Strings",
      "Iteration",
      "Basic recursion",
      "Weekly rhythm: Mon–Fri 1–1.5h, Saturday 2–3h, Sunday 1–2h or rest",
      "Every week is Learn → Practice → Build → Review",
    ],
    practice: [
      "Find maximum / minimum",
      "Reverse an array",
      "Remove duplicates",
      "Count occurrences",
      "Two-sum",
      "Check palindrome",
    ],
    buildTitle: "Algorithm Playground — enter data and see the algorithm's result",
    build: [
      "Scaffold a small playground UI or API",
      "Run at least the six practice algorithms on user input",
      "Show the result, not just a console log",
      "Portfolio piece 1: Algorithm Playground",
    ],
    buildTrack: "frontend",
    checklist: ["Big O explained in your own words", "Playground runs the practice set"],
  }),
  week({
    n: 2,
    month: 1,
    title: "Hash maps + sets",
    goal: "Trade space for fast lookups, then ship a contact search API.",
    learn: ["Hash maps", "Sets", "Frequency counting", "Lookup optimization"],
    practice: [
      "Two Sum",
      "First unique character",
      "Group anagrams",
      "Duplicate detection",
      "Intersection of arrays",
    ],
    buildTitle: "Contact Search API that searches thousands of contacts efficiently",
    build: [
      "GET /contacts",
      "GET /contacts/search?q=daph",
      "POST /contacts",
      "DELETE /contacts/:id",
      "Search must stay fast as the contact list grows",
    ],
  }),
  week({
    n: 3,
    month: 1,
    title: "Two pointers + sliding window",
    goal: "Know when a window or two pointers beats a nested loop. This later helps BeautiLink search.",
    learn: ["Two-pointer technique", "Sliding window", "When to use each"],
    practice: [
      "Longest substring",
      "Maximum sum subarray",
      "Remove duplicates",
      "Valid palindrome",
    ],
    buildTitle: "Product Search / Filter engine",
    build: [
      "Filter products by more than one field",
      "Search without scanning more than you need",
      "Keep the approach reusable for BeautiLink later",
    ],
  }),
  week({
    n: 4,
    month: 1,
    title: "Stack + queue",
    goal: "LIFO and FIFO, then a job processor that previews background work.",
    learn: ["Stack", "Queue", "Deque", "LIFO / FIFO", "Applications"],
    practice: [
      "Valid parentheses",
      "Min stack",
      "Queue implementation",
      "Browser history",
      "Task queue",
    ],
    buildTitle: "Job Processing Simulator",
    build: [
      "Incoming jobs enter a queue",
      "A worker pulls jobs off the queue",
      "Completed jobs are recorded separately",
      "You can explain why this maps to background jobs later",
    ],
  }),
  week({
    n: 5,
    month: 2,
    title: "Linked lists",
    goal: "Pointer manipulation, then an LRU cache you'll later recognize in Redis.",
    learn: [
      "Nodes",
      "Singly linked lists",
      "Doubly linked lists",
      "Fast / slow pointers",
    ],
    practice: [
      "Reverse a linked list",
      "Detect a cycle",
      "Find the middle",
      "Merge two lists",
    ],
    buildTitle: "LRU Cache",
    build: [
      "Implement get and put with O(1) operations",
      "Evict the least recently used item",
      "Write down how this relates to Redis caching later",
    ],
  }),
  week({
    n: 6,
    month: 2,
    title: "Recursion + binary search",
    goal: "Divide and conquer, then a search API over a large dataset.",
    learn: ["Recursion", "Divide and conquer", "Binary search"],
    practice: [
      "Binary search",
      "Search in a rotated array",
      "Recursive tree traversal",
    ],
    buildTitle: "Smart Search Service",
    build: [
      "API that searches a large dataset",
      "API that filters that dataset",
      "Prefer binary search (or an index) over a full scan where it fits",
    ],
  }),
  week({
    n: 7,
    month: 2,
    title: "Trees",
    goal: "Traverse trees on purpose, then model an organization as a tree.",
    learn: ["Binary trees", "BST", "DFS", "BFS", "Tree traversal"],
    practice: ["Inorder", "Preorder", "Postorder", "Level order", "Maximum depth"],
    buildTitle: "Organization Directory",
    build: [
      "Model CEO → departments → teams",
      "Engineering contains Frontend and Backend; Finance is a sibling",
      "Expose traversal of the tree (DFS and BFS)",
    ],
  }),
  week({
    n: 8,
    month: 2,
    title: "Graphs",
    goal: "Represent a network and walk it. This connects to nearby services in BeautiLink.",
    learn: [
      "Graph representation",
      "BFS",
      "DFS",
      "Directed graphs",
      "Undirected graphs",
    ],
    buildTitle: "Location / Service Network",
    build: [
      "Model places such as Nairobi → Kiambu → Limuru",
      "Calculate a route with BFS",
      "Calculate a route with DFS and compare the two",
      "Note how this could power nearby services later",
    ],
    checklist: ["Foundations month pair done", "You can draw a graph and walk it"],
  }),
  week({
    n: 9,
    month: 3,
    title: "HTTP + REST",
    goal: "HTTP stops being magic. Ship a task API with NestJS and PostgreSQL.",
    learn: [
      "HTTP",
      "GET, POST, PUT, PATCH, DELETE",
      "Status codes",
      "Headers",
      "Cookies",
      "CORS",
      "REST principles",
      "API versioning",
    ],
    buildTitle: "Task Management API",
    build: [
      "POST /tasks",
      "GET /tasks",
      "GET /tasks/:id",
      "PATCH /tasks/:id",
      "DELETE /tasks/:id",
      "NestJS + PostgreSQL",
    ],
  }),
  week({
    n: 10,
    month: 3,
    title: "NestJS architecture",
    goal: "Modules, DI, and the request pipeline — then an employee API with roles.",
    learn: [
      "Modules",
      "Controllers",
      "Services",
      "Dependency injection",
      "DTOs",
      "Pipes",
      "Guards",
      "Interceptors",
      "Middleware",
      "Exception filters",
    ],
    buildTitle: "Employee Management API",
    build: ["Users", "Departments", "Roles", "Permissions"],
  }),
  week({
    n: 11,
    month: 3,
    title: "PostgreSQL",
    goal: "Model BeautiLink's core data: people, services, bookings, payments, reviews.",
    learn: [
      "Tables",
      "Relationships",
      "Primary keys",
      "Foreign keys",
      "Joins",
      "Indexes",
      "Transactions",
      "Constraints",
      "Normalization",
    ],
    buildTitle: "Booking database",
    build: [
      "Users",
      "Professionals",
      "Services",
      "Bookings",
      "Payments",
      "Reviews",
      "Relationships and constraints you can explain",
    ],
  }),
  week({
    n: 12,
    month: 3,
    title: "Authentication",
    goal: "A reusable auth service you can drop into later apps.",
    learn: [
      "Password hashing",
      "JWT",
      "Access tokens",
      "Refresh tokens",
      "RBAC",
      "Permissions",
    ],
    buildTitle: "Production-style authentication service",
    build: [
      "Registration",
      "Login",
      "Logout",
      "Refresh token",
      "Forgot password",
      "Reset password",
      "Role permissions",
      "Portfolio piece 2: Authentication Service (NestJS + PostgreSQL + JWT + RBAC)",
    ],
    mini: true,
    checklist: ["Auth is reusable", "Passwords are hashed", "Roles are enforced"],
  }),
  week({
    n: 13,
    month: 4,
    title: "Validation + security",
    goal: "Harden the API you already have instead of starting a new toy app.",
    learn: [
      "Input validation",
      "SQL injection",
      "XSS",
      "CSRF",
      "Rate limiting",
      "Security headers",
      "Password security",
    ],
    buildTitle: "Security pass on your existing API",
    build: [
      "Validate every input that crosses the boundary",
      "Add rate limiting",
      "Add security headers",
      "Review password handling",
      "Write down what you changed and why",
    ],
  }),
  week({
    n: 14,
    month: 4,
    title: "Testing",
    goal: "Test important behavior. Aim for meaningful coverage, not a vanity percentage.",
    learn: ["Unit tests", "Integration tests", "E2E tests", "Jest", "Supertest"],
    buildTitle: "Backend test suite",
    build: [
      "Unit tests for core services",
      "Integration tests for important endpoints",
      "At least one E2E flow",
      "Target 70%+ meaningful coverage — test behavior, not getters",
    ],
  }),
  week({
    n: 15,
    month: 4,
    title: "File uploads + external APIs",
    goal: "Files, then email, SMS, and cloud storage.",
    learn: ["Uploads", "Download", "File validation", "Metadata", "Permissions"],
    buildTitle: "Document Management API",
    build: [
      "Upload",
      "Download",
      "File validation",
      "File metadata",
      "Permissions",
      "Integrate an email API",
      "Integrate an SMS API",
      "Integrate cloud storage",
    ],
  }),
  week({
    n: 16,
    month: 4,
    title: "Background jobs",
    goal: "Work that must not block the request: queue, worker, retry.",
    learn: ["Background processing", "Cron jobs", "Queues", "Workers", "Retry logic"],
    buildTitle: "Notification Service",
    build: [
      "Booking created enqueues a job",
      "A worker consumes the job",
      "Send email, SMS, or push",
      "Retries when delivery fails",
      "Portfolio piece 4 starts here: queues + workers + email/SMS/push",
    ],
  }),
  week({
    n: 17,
    month: 5,
    title: "Redis",
    goal: "Cache the booking API. Know when a cache is lying to you.",
    learn: [
      "Caching",
      "TTL",
      "Key/value storage",
      "Cache invalidation",
      "Sessions",
      "Rate limiting",
    ],
    buildTitle: "Redis on the booking API",
    build: [
      "Cache a hot read path",
      "Set a TTL",
      "Invalidate on write",
      "Use Redis for rate limiting or sessions",
      "Portfolio piece 3: Booking API with PostgreSQL transactions + Redis",
    ],
  }),
  week({
    n: 18,
    month: 5,
    title: "Advanced PostgreSQL",
    goal: "Make the booking system slow on purpose, then make it fast.",
    learn: [
      "Query optimization",
      "Index strategies",
      "EXPLAIN",
      "Transactions",
      "Isolation levels",
      "Locks",
      "Connection pooling",
    ],
    buildTitle: "Optimize the booking system",
    build: [
      "Write a query that is deliberately slow",
      "Read EXPLAIN",
      "Add the right index",
      "Measure the difference",
      "Note pooling and transaction boundaries",
    ],
  }),
  week({
    n: 19,
    month: 5,
    title: "Messaging",
    goal: "One queue, many consumers. Learn the idea — don't master RabbitMQ, Kafka, and Service Bus at once.",
    learn: [
      "Why messaging exists",
      "RabbitMQ concepts",
      "Kafka concepts",
      "Azure Service Bus concepts",
      "Pick one tool and build with it",
    ],
    buildTitle: "Order / Booking Event System",
    build: [
      "Booking Created publishes an event",
      "Email consumer",
      "SMS consumer",
      "Analytics consumer",
      "You can draw the fan-out",
    ],
  }),
  week({
    n: 20,
    month: 5,
    title: "Production readiness",
    goal: "The API should feel deployable, not like a tutorial leftover.",
    learn: [
      "Logging",
      "Error handling",
      "Health checks",
      "Monitoring",
      "Graceful shutdown",
      "Environment configuration",
      "Secrets",
    ],
    buildTitle: "Production-shaped API",
    build: [
      "Structured logs",
      "Consistent errors",
      "Health check endpoint",
      "Graceful shutdown",
      "Secrets stay out of source control",
      "Portfolio piece 5 starts here and finishes in the CI/CD weeks",
    ],
    checklist: ["Health check works", "You can explain startup and shutdown"],
  }),
  week({
    n: 21,
    month: 6,
    title: "Scalability basics",
    goal: "Design a URL shortener and defend the tradeoffs.",
    learn: ["Scalability", "Availability", "Reliability", "Latency", "Throughput"],
    buildTitle: "Design: URL Shortener",
    build: [
      "Write the requirements",
      "Sketch the API and data model",
      "Explain read vs write traffic",
      "Call out failure modes",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 22,
    month: 6,
    title: "Scaling + caching + CDN",
    goal: "Design an image service and say where a CDN earns its keep.",
    learn: [
      "Load balancers",
      "Horizontal scaling",
      "Vertical scaling",
      "Caching",
      "CDN",
    ],
    buildTitle: "Design: Instagram-like image service",
    build: [
      "Upload path vs read path",
      "Where the load balancer sits",
      "What you cache",
      "What the CDN serves",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 23,
    month: 6,
    title: "Event-driven design",
    goal: "Design a notification platform as events, not as one giant function.",
    learn: ["Queues", "Event-driven architecture", "Async processing"],
    buildTitle: "Design: Notification platform",
    build: [
      "Producers and consumers",
      "What is synchronous vs queued",
      "Retries and dead letters",
      "How this matches the service you already built",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 24,
    month: 6,
    title: "Design BeautiLink",
    goal: "An architecture diagram you can talk through in an interview or portfolio review.",
    learn: [
      "Compose auth, bookings, data, cache, queues, notifications, and payments",
      "Every box needs a reason",
    ],
    buildTitle: "BeautiLink architecture",
    build: [
      "Mobile app → API",
      "Authentication",
      "Booking service",
      "PostgreSQL",
      "Redis",
      "Message queue",
      "Notifications",
      "Payments",
      "Write a short explanation of every component",
    ],
    buildTrack: "shared",
    mini: true,
    checklist: ["Diagram exists", "You can explain every box"],
  }),
  week({
    n: 25,
    month: 7,
    title: "Docker",
    goal: "One command brings up the API, Postgres, and Redis.",
    learn: ["Images", "Containers", "Dockerfile", "Docker Compose", "Volumes", "Networks"],
    buildTitle: "Containerize the stack",
    build: ["NestJS image", "PostgreSQL", "Redis", "Compose file you can run locally"],
  }),
  week({
    n: 26,
    month: 7,
    title: "Git properly",
    goal: "Use Git the way a team does, not as a save button.",
    learn: [
      "Branching",
      "Rebasing",
      "Cherry-picking",
      "Pull requests",
      "Conflict resolution",
      "Conventional commits",
    ],
    buildTitle: "Team-style Git practice",
    build: [
      "Branch for a real change",
      "Open a pull request",
      "Resolve a conflict on purpose",
      "Write conventional commit messages",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 27,
    month: 7,
    title: "CI",
    goal: "A push runs tests, lint, and a build. Red means you don't merge.",
    learn: [
      "GitHub Actions",
      "Automated tests",
      "Build pipelines",
      "Linting",
      "Security checks",
    ],
    buildTitle: "CI pipeline",
    build: [
      "git push → GitHub",
      "Tests",
      "Build",
      "Pass / fail is visible",
      "Lint and a basic security check",
    ],
  }),
  week({
    n: 28,
    month: 7,
    title: "CD",
    goal: "Push, test, image, deploy, health check. That is a real CI/CD project.",
    learn: ["Continuous delivery", "Image publishing", "Deploy hooks", "Health checks"],
    buildTitle: "Deploy the backend",
    build: [
      "Push",
      "Test",
      "Build Docker image",
      "Deploy",
      "Health check",
      "Portfolio piece 5: Docker + testing + CI/CD + monitoring",
    ],
    checklist: ["Pipeline is green", "Deployed API answers a health check"],
  }),
  week({
    n: 29,
    month: 8,
    title: "Cloud concepts",
    goal: "Start AZ-900. Know what you are renting.",
    learn: [
      "Cloud concepts",
      "IaaS",
      "PaaS",
      "SaaS",
      "Regions",
      "Availability zones",
      "Azure subscriptions",
    ],
    buildTitle: "AZ-900 notes you wrote yourself",
    build: [
      "Define IaaS, PaaS, and SaaS with your own examples",
      "Explain regions vs availability zones",
      "Explain subscriptions and resource groups",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 30,
    month: 8,
    title: "Azure data services",
    goal: "Know which Azure data service is for which job.",
    learn: ["Azure Storage", "Blob Storage", "Azure SQL", "Cosmos DB", "Databases"],
    buildTitle: "Data-service comparison",
    build: [
      "When you would use Blob vs a relational database",
      "When Cosmos DB is the wrong default",
      "Map your booking data to Azure SQL, not to a new database for fun",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 31,
    month: 8,
    title: "Azure compute",
    goal: "Pick a compute option on purpose.",
    learn: ["App Service", "Virtual Machines", "Containers", "Functions"],
    buildTitle: "Compute decision for your NestJS API",
    build: [
      "Why App Service fits the API",
      "What you would not put on a VM",
      "What belongs in a Function instead of the API",
    ],
    buildTrack: "shared",
  }),
  week({
    n: 32,
    month: 8,
    title: "Identity, network, security",
    goal: "Practice for AZ-900. Identity and monitoring are part of the exam, not extras.",
    learn: ["Entra ID", "RBAC", "Networking", "Security", "Monitoring"],
    buildTitle: "AZ-900 practice",
    build: [
      "Practice questions",
      "Explain RBAC in your own words",
      "Explain a simple network boundary",
      "Sit a practice exam or a timed review",
    ],
    buildTrack: "shared",
    checklist: ["AZ-900 practice done"],
  }),
  week({
    n: 33,
    month: 9,
    title: "Azure App Service",
    goal: "The NestJS API runs on App Service.",
    learn: ["App Service", "Deployment slots if you use them", "Configuration", "Scaling basics"],
    buildTitle: "Deploy NestJS to App Service",
    build: [
      "Deploy the API",
      "Configuration comes from app settings, not the repo",
      "You can hit a real URL",
    ],
  }),
  week({
    n: 34,
    month: 9,
    title: "Azure Functions",
    goal: "A scheduled job that does not live inside the API process.",
    learn: ["Azure Functions", "Timer triggers", "Blob output", "Email"],
    buildTitle: "Scheduled Report Generator",
    build: [
      "Every Monday a function runs",
      "It generates a report",
      "It stores the report in Blob",
      "It emails the user",
      "Portfolio piece 6: Functions + Storage + Service Bus (Service Bus lands in week 37)",
    ],
  }),
  week({
    n: 35,
    month: 9,
    title: "Azure Storage",
    goal: "Documents live in Blob with rules, not on the server disk.",
    learn: ["Blob containers", "Access", "Metadata", "Lifecycle"],
    buildTitle: "Document storage service",
    build: [
      "Upload to Blob",
      "Download with permission checks",
      "Store metadata",
      "You can say who is allowed to read a file",
    ],
  }),
  week({
    n: 36,
    month: 9,
    title: "Azure SQL",
    goal: "Move part of the project off local PostgreSQL and notice what changes.",
    learn: ["Azure SQL", "Connection strings", "Differences from PostgreSQL", "Backups at a high level"],
    buildTitle: "Azure SQL integration",
    build: [
      "Move one slice of the app to Azure SQL",
      "Write down what you had to change",
      "Keep PostgreSQL knowledge — this is a comparison, not a rewrite of everything",
    ],
  }),
  week({
    n: 37,
    month: 10,
    title: "Azure Service Bus",
    goal: "Replace the local queue in the notification system.",
    learn: ["Queues", "Topics", "Subscriptions", "Retries", "Dead-letter"],
    buildTitle: "Notifications on Service Bus",
    build: [
      "Publish booking/notification events to Service Bus",
      "A worker consumes them",
      "Failures land somewhere you can see",
      "Portfolio piece 6 is now Functions + Storage + Service Bus",
    ],
  }),
  week({
    n: 38,
    month: 10,
    title: "Entra ID",
    goal: "Identity that isn't only a JWT you signed yourself.",
    learn: ["Authentication", "Roles", "Permissions", "Application identity"],
    buildTitle: "Entra ID integration",
    build: [
      "Sign-in through Entra ID",
      "Roles",
      "Permissions",
      "An application identity for service-to-service calls",
    ],
  }),
  week({
    n: 39,
    month: 10,
    title: "Key Vault",
    goal: "Secrets leave the app config.",
    learn: ["Key Vault", "Managed identity or app identity", "Rotation mindset"],
    buildTitle: "Secrets in Key Vault",
    build: [
      "Move JWT_SECRET",
      "Move DATABASE_URL",
      "Move API keys",
      "The app reads them at runtime, not from a committed file",
    ],
  }),
  week({
    n: 40,
    month: 10,
    title: "Application Insights",
    goal: "You can see failures without SSHing anywhere.",
    learn: ["Logs", "Metrics", "Traces", "Alerts", "Application performance"],
    buildTitle: "Monitoring on the API",
    build: [
      "Application Insights is receiving telemetry",
      "You can find a failed request",
      "One alert exists for something you care about",
      "You looked at a slow request on purpose",
    ],
    checklist: ["Logs, metrics, and one alert"],
  }),
  week({
    n: 41,
    month: 11,
    title: "SQL Server",
    goal: "T-SQL is a tool, not a new career detour.",
    learn: ["T-SQL", "Stored procedures", "Views", "Indexes", "Transactions"],
    buildTitle: "SQL Server exercises against real tables",
    build: [
      "Write queries you would actually ship",
      "One view",
      "One stored procedure with a reason to exist",
      "Indexes you can justify",
    ],
  }),
  week({
    n: 42,
    month: 11,
    title: "Advanced SQL",
    goal: "Read an execution plan instead of guessing.",
    learn: ["Window functions", "CTEs", "Query optimization", "Execution plans"],
    practice: [
      "Window function query",
      "CTE that makes a query readable",
      "A slow query you then fix",
    ],
    buildTitle: "Optimized reporting queries",
    build: [
      "One report query using a window function",
      "Read its execution plan",
      "Change it and record the difference",
    ],
  }),
  week({
    n: 43,
    month: 11,
    title: "ETL",
    goal: "Data moves in stages. Broken rows do not silently vanish.",
    learn: ["Source", "Extract", "Transform", "Validate", "Load"],
    buildTitle: "Healthcare / business data pipeline",
    build: [
      "Extract from a source file or API",
      "Transform",
      "Validate and reject bad rows",
      "Load",
      "Portfolio piece 7 starts here",
    ],
  }),
  week({
    n: 44,
    month: 11,
    title: "Azure Data Factory",
    goal: "The pipeline is a product, not a script only you can run.",
    learn: ["Pipelines", "Datasets", "Copy and transform", "Triggers"],
    buildTitle: "Data Factory pipeline",
    build: [
      "CSV or API source",
      "Data Factory",
      "Transformation",
      "SQL Server",
      "A dashboard or report at the end",
      "Portfolio piece 7: SQL Server + Data Factory",
    ],
    checklist: ["Pipeline runs", "You can show the output"],
  }),
  week({
    n: 45,
    month: 12,
    title: "Enterprise API integrations",
    goal: "Use the insurance domain you already know. Integrate, don't reinvent the provider.",
    learn: ["Partner APIs", "Idempotency", "Timeouts", "Mapping external models"],
    buildTitle: "Insurance Integration Platform",
    build: [
      "Frontend calls your API",
      "Your API calls an insurance provider API",
      "Policy system",
      "Payment",
      "Notification",
    ],
    buildTrack: "backend",
  }),
  week({
    n: 46,
    month: 12,
    title: "Legacy integration",
    goal: "Old systems are files, XML, and schedules. Meet them where they are.",
    learn: ["SOAP basics", "XML", "File-based integrations", "Scheduled jobs", "Legacy databases"],
    buildTitle: "Mock legacy integration",
    build: [
      "Consume or emit XML or a flat file",
      "Run it on a schedule",
      "Write to or read from a 'legacy' table",
      "Document the contract",
    ],
  }),
  week({
    n: 47,
    month: 12,
    title: "Security + performance audit",
    goal: "Attack your own major project, then fix what you find.",
    learn: [
      "Authentication weaknesses",
      "Injection",
      "Rate limits",
      "Slow queries",
      "Large payloads",
      "Failed and duplicate requests",
    ],
    buildTitle: "Audit and fix",
    build: [
      "Try an authentication bypass or weak token flow",
      "Try SQL injection",
      "Hammer an endpoint that should be rate limited",
      "Find a slow query",
      "Send a large payload and a duplicate request",
      "Fix everything you can reproduce",
    ],
    reviewDay: true,
    checklist: ["Findings written down", "Fixes merged"],
  }),
  week({
    n: 48,
    month: 12,
    title: "Capstone",
    goal: "Enterprise Booking & Marketplace — a production-grade evolution of BeautiLink.",
    learn: [
      "You already have the pieces. This week assembles them.",
      "Use Cursor or Claude to move faster, but you must be able to explain the architecture and the code.",
      "Do not add Kubernetes, AWS, GCP, Go, Java, Rust, deep GraphQL, deep Kafka, deep Terraform, or a new frontend framework.",
    ],
    buildTitle: "Enterprise Booking & Marketplace Platform",
    build: [
      "Frontend: React/Next.js or Expo",
      "Backend: NestJS",
      "Database: PostgreSQL or SQL Server",
      "Cache: Redis",
      "Messaging: Azure Service Bus",
      "Auth: Entra ID + JWT",
      "Storage: Azure Blob",
      "Host: Azure App Service",
      "Background work: Azure Functions",
      "Monitoring: Application Insights",
      "CI/CD: GitHub Actions or Azure DevOps",
      "Tests: Jest + one E2E path",
      "Docs: Swagger / OpenAPI",
      "README a stranger can follow",
      "Portfolio piece 8: everything together",
    ],
    buildTrack: "backend",
    mini: true,
    checklist: [
      "Deployed",
      "Documented",
      "You can explain every major component without notes",
    ],
  }),
];

export const YEAR_ROADMAP: RoadmapDefinition = {
  id: YEAR_ROADMAP_ID,
  title: "12-Month Backend & Cloud",
  description:
    "8–12 hours a week. Every week is Learn → Practice → Build → Review, with DSA running all year. Stack: TypeScript, NestJS, PostgreSQL, Redis, Docker, CI/CD, Azure, SQL Server. Finish with eight portfolio pieces, not fifteen CRUD apps. Rule: learn, build, break it, debug it, test it, deploy it, document it.",
  tags: ["12 months", "DSA", "NestJS", "Azure", "DevOps"],
  accent: "24 90% 48%",
  itemLabel: "Week",
  groupLabel: "Month",
  timeBlocks: DEFAULT_TIME_BLOCKS,
  weekGoals: YEAR_MONTH_GOALS,
  days: YEAR_ROADMAP_WEEKS,
  outcomes: [
    "Algorithm Playground",
    "Authentication service with JWT and RBAC",
    "Booking API with PostgreSQL and Redis",
    "Notification system on queues and workers",
    "Production API: Docker, tests, CI/CD, monitoring",
    "Azure serverless app: Functions, Storage, Service Bus",
    "ETL pipeline: SQL Server and Data Factory",
    "Enterprise booking marketplace capstone",
  ],
};
